import type {
  AnimationName,
  EffectName,
  TextClip,
  TransitionName,
} from "./model";
export const FILTERS = [
  { name: "Original", css: "", color: "#6a839a" },
  { name: "Fresh", css: "saturate(1.25) contrast(1.04)", color: "#5bbaa5" },
  {
    name: "Cinema",
    css: "sepia(.23) saturate(.8) contrast(1.15)",
    color: "#af8c6e",
  },
  { name: "Mono", css: "grayscale(1) contrast(1.18)", color: "#a4a4ad" },
  { name: "Warm", css: "sepia(.28) saturate(1.2)", color: "#e6ae6f" },
  {
    name: "Dream",
    css: "saturate(.75) contrast(.88) brightness(1.12)",
    color: "#b2a1e9",
  },
  {
    name: "Arctic",
    css: "sepia(.18) hue-rotate(155deg) saturate(.85)",
    color: "#79b7d9",
  },
  {
    name: "Vintage",
    css: "sepia(.55) contrast(.85) saturate(.8)",
    color: "#b8a079",
  },
  {
    name: "Noir",
    css: "grayscale(1) contrast(1.65) brightness(.88)",
    color: "#797c89",
  },
  {
    name: "Teal & orange",
    css: "sepia(.35) hue-rotate(335deg) saturate(1.4) contrast(1.08)",
    color: "#67b4bb",
  },
  {
    name: "Faded",
    css: "contrast(.72) brightness(1.12) saturate(.68)",
    color: "#c1b6b4",
  },
  { name: "Vivid", css: "saturate(1.65) contrast(1.12)", color: "#d18cca" },
];
export const EFFECTS: {
  name: EffectName;
  description: string;
  icon: string;
  color: string;
  category: "Essentials" | "Light" | "Texture" | "Distortion" | "Stylize" | "Motion";
  defaultAmount: number;
}[] = [
  {
    name: "Vignette",
    description: "Soft, darker edges",
    icon: "◉",
    color: "#93aaa9",
    category: "Essentials", defaultAmount: 45,
  },
  {
    name: "Grain",
    description: "Moving film texture",
    icon: "⠿",
    color: "#ac998a",
    category: "Texture", defaultAmount: 35,
  },
  {
    name: "Glow",
    description: "Soft luminous bloom",
    icon: "✦",
    color: "#b8a6ee",
    category: "Light", defaultAmount: 45,
  },
  { name: "Blur", description: "Defocused image", icon: "◌", color: "#82a4d6", category: "Essentials", defaultAmount: 35 },
  {
    name: "Pixelate",
    description: "Retro pixel blocks",
    icon: "▦",
    color: "#83ba9d",
    category: "Stylize", defaultAmount: 45,
  },
  {
    name: "Chromatic",
    description: "Split color channels",
    icon: "≋",
    color: "#d680b5",
    category: "Distortion", defaultAmount: 40,
  },
  {
    name: "Scanlines",
    description: "Analog display lines",
    icon: "☰",
    color: "#88bca5",
    category: "Texture", defaultAmount: 45,
  },
  {
    name: "Duotone",
    description: "Two-color treatment",
    icon: "◐",
    color: "#b789d4",
    category: "Stylize", defaultAmount: 65,
  },
  {
    name: "Shake",
    description: "Handheld camera motion",
    icon: "↯",
    color: "#d1af79",
    category: "Motion", defaultAmount: 35,
  },
  { name: "Pulse", description: "Rhythmic zoom", icon: "◎", color: "#c894bd", category: "Motion", defaultAmount: 40 },
  {
    name: "Letterbox",
    description: "Cinematic frame",
    icon: "▬",
    color: "#8c9ebf",
    category: "Essentials", defaultAmount: 65,
  },
  {
    name: "Prism",
    description: "Color light wash",
    icon: "◇",
    color: "#95a8e0",
    category: "Light", defaultAmount: 50,
  },
  {
    name: "Wavy",
    description: "Flowing horizontal wave distortion",
    icon: "〰",
    color: "#70c8d6",
    category: "Distortion", defaultAmount: 50,
  },
  { name: "Soft focus", description: "Velvety diffusion with retained detail", icon: "✺", color: "#c7b1e5", category: "Light", defaultAmount: 50 },
  { name: "Directional blur", description: "Horizontal shutter streaks", icon: "⇢", color: "#94b5df", category: "Light", defaultAmount: 40 },
  { name: "Zoom blur", description: "Light streaks radiating from the center", icon: "⊙", color: "#bc98df", category: "Light", defaultAmount: 40 },
  { name: "Radial blur", description: "Rotating long-exposure blur", icon: "↻", color: "#98b7d6", category: "Light", defaultAmount: 35 },
  { name: "Tilt shift", description: "Miniature focus with soft outer bands", icon: "═", color: "#a7bed7", category: "Light", defaultAmount: 50 },
  { name: "Light leak", description: "Animated amber and rose film flare", icon: "◒", color: "#e2a489", category: "Light", defaultAmount: 45 },
  { name: "Film dust", description: "Deterministic moving dust and flecks", icon: "⁙", color: "#bcb1a1", category: "Texture", defaultAmount: 45 },
  { name: "Film scratches", description: "Fine drifting celluloid scratches", icon: "╱", color: "#b8a390", category: "Texture", defaultAmount: 45 },
  { name: "Flicker", description: "Organic analog exposure fluctuation", icon: "◔", color: "#e0b68f", category: "Motion", defaultAmount: 45 },
  { name: "Strobe", description: "Rhythmic hard exposure flashes", icon: "ϟ", color: "#d5c3e7", category: "Motion", defaultAmount: 40 },
  { name: "Posterize", description: "Graphic reduced-tone color bands", icon: "▥", color: "#bca3e0", category: "Stylize", defaultAmount: 65 },
  { name: "Negative", description: "Smoothly mix an inverted color negative", icon: "◑", color: "#a4bfd7", category: "Stylize", defaultAmount: 100 },
  { name: "Solarize", description: "Reversed highlights with surreal color", icon: "◭", color: "#ddb386", category: "Stylize", defaultAmount: 75 },
  { name: "Halftone", description: "Luminance-based printed dot screen", icon: "⠶", color: "#aca2ce", category: "Stylize", defaultAmount: 70 },
  { name: "Edge glow", description: "Colored neon outlines from real edges", icon: "⌁", color: "#81c5d0", category: "Stylize", defaultAmount: 65 },
  { name: "Sketch", description: "Paper and charcoal edge illustration", icon: "✎", color: "#bfb8aa", category: "Stylize", defaultAmount: 90 },
  { name: "Fisheye", description: "Wide-angle spherical lens warping", icon: "◉", color: "#91b6d7", category: "Distortion", defaultAmount: 55 },
  { name: "Swirl", description: "Smooth vortex around the clip center", icon: "◌", color: "#b9a0dc", category: "Distortion", defaultAmount: 50 },
  { name: "Ripple", description: "Animated concentric water refraction", icon: "◎", color: "#88c8d1", category: "Distortion", defaultAmount: 50 },
  { name: "Kaleidoscope", description: "Six mirrored optical sectors", icon: "✧", color: "#c7a4db", category: "Distortion", defaultAmount: 70 },
  { name: "Mirror", description: "Fold the left half into a symmetric image", icon: "↔", color: "#9bb5cb", category: "Distortion", defaultAmount: 100 },
];
export type TransitionCategory = "Classic" | "Movement" | "Reveal" | "Light" | "Distortion";
export const TRANSITIONS: {
  name: TransitionName; icon: string; category: TransitionCategory; description: string; color: string;
}[] = [
  { name: "None", icon: "—", category: "Classic", description: "A clean, immediate cut", color: "#7c8c9d" },
  { name: "Dissolve", icon: "◐", category: "Classic", description: "A balanced, smooth crossfade", color: "#a5b8ce" },
  { name: "Fade black", icon: "●", category: "Light", description: "Dip both shots through black", color: "#8896ab" },
  { name: "Fade white", icon: "○", category: "Light", description: "Dip both shots through white", color: "#ead8ba" },
  { name: "Blur", icon: "◌", category: "Distortion", description: "Focus melts softly between shots", color: "#a8bfea" },
  { name: "Glitch", icon: "≋", category: "Distortion", description: "A brief color-shifted digital jump", color: "#c99fe5" },
  { name: "Wipe left", icon: "◧", category: "Reveal", description: "Reveal from the right edge", color: "#86cbb6" },
  { name: "Wipe right", icon: "◨", category: "Reveal", description: "Reveal from the left edge", color: "#86cbb6" },
  { name: "Wipe up", icon: "⬒", category: "Reveal", description: "Reveal from the bottom edge", color: "#86cbb6" },
  { name: "Wipe down", icon: "⬓", category: "Reveal", description: "Reveal from the top edge", color: "#86cbb6" },
  { name: "Diagonal top left", icon: "↘", category: "Reveal", description: "A diagonal sweep from the top left", color: "#82c4ce" },
  { name: "Diagonal top right", icon: "↙", category: "Reveal", description: "A diagonal sweep from the top right", color: "#82c4ce" },
  { name: "Diagonal bottom left", icon: "↗", category: "Reveal", description: "A diagonal sweep from the bottom left", color: "#82c4ce" },
  { name: "Diagonal bottom right", icon: "↖", category: "Reveal", description: "A diagonal sweep from the bottom right", color: "#82c4ce" },
  { name: "Slide left", icon: "←", category: "Movement", description: "Push both shots smoothly to the left", color: "#94aee4" },
  { name: "Slide right", icon: "→", category: "Movement", description: "Push both shots smoothly to the right", color: "#94aee4" },
  { name: "Slide up", icon: "↑", category: "Movement", description: "Push both shots smoothly upward", color: "#94aee4" },
  { name: "Slide down", icon: "↓", category: "Movement", description: "Push both shots smoothly downward", color: "#94aee4" },
  { name: "Push up left", icon: "↖", category: "Movement", description: "Move both frames diagonally up left", color: "#a3a1e3" },
  { name: "Push up right", icon: "↗", category: "Movement", description: "Move both frames diagonally up right", color: "#a3a1e3" },
  { name: "Zoom", icon: "◎", category: "Movement", description: "Move gently into the next shot", color: "#bcace6" },
  { name: "Zoom out", icon: "⊙", category: "Movement", description: "Pull back as the next shot settles", color: "#bcace6" },
  { name: "Cross zoom", icon: "⦿", category: "Movement", description: "A fast, seamless zoom-through", color: "#bcace6" },
  { name: "Spin clockwise", icon: "↻", category: "Movement", description: "Quarter-turn clockwise crossfade", color: "#c4a9d8" },
  { name: "Spin counterclockwise", icon: "↺", category: "Movement", description: "Quarter-turn counterclockwise crossfade", color: "#c4a9d8" },
  { name: "Flip horizontal", icon: "⇋", category: "Movement", description: "Fold through a horizontal card flip", color: "#a6b4cf" },
  { name: "Flip vertical", icon: "⇵", category: "Movement", description: "Fold through a vertical card flip", color: "#a6b4cf" },
  { name: "Whip left", icon: "⇠", category: "Distortion", description: "A fast leftward pan with soft blur", color: "#dab28d" },
  { name: "Whip right", icon: "⇢", category: "Distortion", description: "A fast rightward pan with soft blur", color: "#dab28d" },
  { name: "Whip up", icon: "⇡", category: "Distortion", description: "A fast upward pan with soft blur", color: "#dab28d" },
  { name: "Whip down", icon: "⇣", category: "Distortion", description: "A fast downward pan with soft blur", color: "#dab28d" },
  { name: "Circle", icon: "◉", category: "Reveal", description: "Open a circular iris from the center", color: "#99c4aa" },
  { name: "Iris close", icon: "⊚", category: "Reveal", description: "Close the outgoing frame inward", color: "#99c4aa" },
  { name: "Diamond", icon: "◇", category: "Reveal", description: "A crisp diamond-shaped center reveal", color: "#8fc4c3" },
  { name: "Heart", icon: "♡", category: "Reveal", description: "Grow a smooth heart-shaped reveal", color: "#d9a0b4" },
  { name: "Star", icon: "☆", category: "Reveal", description: "A five-point star opens into the shot", color: "#d0c199" },
  { name: "Clock clockwise", icon: "◴", category: "Reveal", description: "Sweep around the frame clockwise", color: "#a2bfbf" },
  { name: "Clock counterclockwise", icon: "◷", category: "Reveal", description: "Sweep around the frame counterclockwise", color: "#a2bfbf" },
  { name: "Split horizontal", icon: "═", category: "Reveal", description: "Open horizontally from the center", color: "#9dbece" },
  { name: "Split vertical", icon: "║", category: "Reveal", description: "Open vertically from the center", color: "#9dbece" },
  { name: "Blinds horizontal", icon: "☰", category: "Reveal", description: "Reveal through eight horizontal bands", color: "#a8c3bf" },
  { name: "Blinds vertical", icon: "▥", category: "Reveal", description: "Reveal through eight vertical bands", color: "#a8c3bf" },
  { name: "Checkerboard", icon: "▦", category: "Reveal", description: "A geometric grid opens tile by tile", color: "#a1bbd3" },
  { name: "Diagonal stripes", icon: "╱", category: "Reveal", description: "Reveal through precise diagonal bands", color: "#a1bbd3" },
  { name: "Shutter", icon: "▱", category: "Reveal", description: "Eight blades glide open from the center", color: "#bab5d0" },
];
export const ANIMATIONS: AnimationName[] = [
  "None",
  "Fade",
  "Rise",
  "Drop",
  "Slide",
  "Slide right",
  "Pop",
  "Zoom",
  "Shrink",
  "Spin",
  "Flip",
  "Bounce",
  "Elastic",
  "Blur",
  "Wipe left",
  "Wipe right",
  "Wipe up",
  "Wipe down",
  "Typewriter",
  "Letter Pop In",
  "Letter Fade",
  "Letter Slide",
  "Letter Blur",
  "Letter Spin",
  "Letter Bounce",
  "Letter Flip",
  "Word Pop",
  "Line Slide",
  "Drift",
  "Custom",
];
export const BUNDLED_FONTS = [
  "Manrope Variable",
  "Source Code Pro Variable",
  "Inter Variable",
  "Roboto Variable",
  "Montserrat Variable",
  "Open Sans Variable",
  "Oswald Variable",
  "Playfair Display Variable",
  "DM Sans Variable",
  "Space Grotesk Variable",
  "Nunito Sans Variable",
];
export const COMMON_SYSTEM_FONTS = [
  "Aptos",
  "Arial",
  "Arial Black",
  "Bahnschrift",
  "Calibri",
  "Cambria",
  "Candara",
  "Century Gothic",
  "Comic Sans MS",
  "Consolas",
  "Corbel",
  "Courier New",
  "Franklin Gothic Medium",
  "Garamond",
  "Georgia",
  "Impact",
  "Lucida Console",
  "Palatino Linotype",
  "Segoe UI",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
];
export const FONTS = [
  ...BUNDLED_FONTS,
  ...COMMON_SYSTEM_FONTS,
];
export const TEXT_PRESETS: {
  name: string;
  sample: string;
  style: Partial<TextClip>;
}[] = [
  {
    name: "Clean title",
    sample: "New Text",
    style: { fontSize: 86, fontWeight: 800 },
  },
  {
    name: "Editorial",
    sample: "New Text",
    style: {
      fontFamily: "Georgia",
      fontSize: 80,
      italic: true,
      fontWeight: 400,
      color: "#f2e7d2",
    },
  },
  {
    name: "Bold outline",
    sample: "New Text",
    style: {
      fontSize: 98,
      fontWeight: 800,
      strokeWidth: 5,
      strokeColor: "#131824",
      shadowBlur: 0,
    },
  },
  {
    name: "Neon",
    sample: "New Text",
    style: {
      fontSize: 80,
      color: "#92ffdb",
      shadowColor: "#35ffb6",
      shadowBlur: 30,
      shadowOffset: 0,
      letterSpacing: 4,
    },
  },
  {
    name: "Caption pill",
    sample: "New Text",
    style: {
      fontSize: 46,
      background: true,
      backgroundColor: "#151820",
      backgroundOpacity: 0.9,
      radius: 26,
      padding: 18,
      y: 0.84,
      kind: "caption",
    },
  },
  {
    name: "Highlight",
    sample: "New Text",
    style: {
      fontSize: 64,
      color: "#172019",
      background: true,
      backgroundColor: "#c0ff82",
      backgroundOpacity: 1,
      radius: 3,
      padding: 20,
      shadowBlur: 0,
    },
  },
  {
    name: "Lower third",
    sample: "New Text",
    style: {
      fontSize: 50,
      align: "left",
      x: 0.08,
      y: 0.78,
      background: true,
      padding: 24,
      radius: 0,
      lineHeight: 1.45,
    },
  },
  {
    name: "Typewriter",
    sample: "New Text",
    style: {
      fontFamily: "Source Code Pro Variable",
      fontSize: 58,
      fontWeight: 500,
      animation: "Typewriter",
      animationDuration: 1.4,
    },
  },
  {
    name: "Pop in",
    sample: "New Text",
    style: {
      fontFamily: "Impact",
      fontSize: 104,
      color: "#ffd16d",
      strokeWidth: 3,
      animation: "Pop",
      rotation: -5,
    },
  },
  {
    name: "Minimal",
    sample: "New Text",
    style: {
      fontSize: 42,
      fontWeight: 400,
      letterSpacing: 6,
      shadowBlur: 0,
      animation: "Fade",
    },
  },
  {
    name: "Glass",
    sample: "New Text",
    style: {
      fontSize: 60,
      background: true,
      backgroundColor: "#788aa0",
      backgroundOpacity: 0.38,
      radius: 18,
      padding: 26,
      letterSpacing: 3,
    },
  },
  {
    name: "Retro",
    sample: "New Text",
    style: {
      fontFamily: "Impact",
      fontSize: 110,
      color: "#ffc792",
      strokeColor: "#72385b",
      strokeWidth: 7,
      shadowColor: "#72385b",
      shadowOffset: 8,
      shadowBlur: 0,
    },
  },
  {
    name: "Aurora gradient",
    sample: "New Text",
    style: {
      fontSize: 86,
      fontWeight: 800,
      fillMode: "linear",
      gradientAngle: 20,
      gradientStops: [
        { id: "start", position: 0, color: "#a8ffe2" },
        { id: "middle", position: 0.5, color: "#78b8ff" },
        { id: "end", position: 1, color: "#d7a2ff" },
      ],
    },
  },
  {
    name: "Sunset gradient",
    sample: "New Text",
    style: {
      fontSize: 86,
      fontWeight: 800,
      fillMode: "linear",
      gradientAngle: 45,
      gradientStops: [
        { id: "start", position: 0, color: "#ffe08e" },
        { id: "middle", position: 0.5, color: "#fc8b8a" },
        { id: "end", position: 1, color: "#b885ff" },
      ],
    },
  },
];
